path:
  url: "https://github.com/eishkina-estia/ML2023/raw/main/data/New_York_City_Taxi_Trip_Duration.zip"
  extract_csv: "./data/row"
  extract_db: "./data/processed"
  model: "./models"

value:
  filename_data: "New_York_City_Taxi_Trip_Duration.csv"
  database_name: "dataset.db"
  model_name: "model.joblib"